# Generated by Django 4.1.3 on 2022-11-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploads',
            old_name='my_file',
            new_name='my_files',
        ),
    ]
