# Generated by Django 4.1.3 on 2022-12-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_my_file_fileuploads_my_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Enter first name')),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Enter Email')),
            ],
        ),
    ]
